var elements = [
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 0, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 0, inversion: "first"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 0, inversion: "second"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 0, inversion: "root"},
    {type: MusicalElement.MusicalElementType.DIMINISHED_CHORD, root: 0, inversion: "root"},
    {type: MusicalElement.MusicalElementType.AUGMENTED_CHORD, root: 0, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 1, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 1, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 2, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 2, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 3, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 3, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 4, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 4, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 5, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 5, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 6, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 6, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 7, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 7, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 8, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 8, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 9, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 9, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 10, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 10, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_CHORD, root: 11, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MINOR_CHORD, root: 11, inversion: "root"},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 0},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 0},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 1},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 1},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 2},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 2},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 3},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 3},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 4},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 4},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 5},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 5},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 6},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 6},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 7},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 7},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 8},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 8},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 9},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 9},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 10},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 10},
    {type: MusicalElement.MusicalElementType.MAJOR_SCALE, root: 11},
    {type: MusicalElement.MusicalElementType.MINOR_SCALE, root: 11}
];